In [ ]:
num=4
for i in range(1, 11):
  print(num*i)

4
8
12
16
20
24
28
32
36
40


In [ ]:
fact=1
i=1
while i<=5:
  fact*=i
  i +=1
  print("fact:", fact)


fact: 1
fact: 2
fact: 6
fact: 24
fact: 120


In [ ]:
num=4
while(i<=4):
  print(num*i)


In [ ]:
num = int(input("Enter the number value: "))
i = 2

while i < num:
    if num % i == 0:
        print("Not prime number")
        break
    i += 1
else:
    print("Prime number")


Enter the number value: 2
Prime number


In [ ]:
sum=0
i=1
while i<=10:
  sum=sum+i
  i=i+1
  print("sum of N natural numbers is :",sum)

sum of N natural numbers is : 1
sum of N natural numbers is : 3
sum of N natural numbers is : 6
sum of N natural numbers is : 10
sum of N natural numbers is : 15
sum of N natural numbers is : 21
sum of N natural numbers is : 28
sum of N natural numbers is : 36
sum of N natural numbers is : 45
sum of N natural numbers is : 55


In [ ]:
num=7
count=0
for i in range(1,num+1):
  if num%i==0:
    count +=1
if count==2:
  print("prime number")
else:
  print("Not prime number")

prime number


In [ ]:
n=int(input("enter number"))
a,b=0,1
for i in range(n):
  print(a,end=" ")
  a,b=b,a+b

enter number20
0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 

In [ ]:
def fun():
  print("hello world")

fun()


hello world


In [ ]:
def add(x,y):
 print("Addition of two number is:",x+y)
add(100,200)
add(24,55)
add(12,33)
add(22,56)

Addition of two number is: 300
Addition of two number is: 79
Addition of two number is: 45
Addition of two number is: 78


In [ ]:
def details(USN_Number,Name,college,place,marks,sem):
  print(f"My name is {Name}; I'am studying in{sem} semster in{college} college at {place} and my USN number is {USN_Number} ")
details(118,"saniya","KLE","Gadag",467,"5th")


My name is saniya; I'am studying in5th semster inKLE college atGadag and my USN number is 118


In [ ]:
def information(Emp_id,Emp_name,Emp_Age ,Emp_salary,Company_Name,location,Phone_number):
  print()
information()

In [ ]:
def college(name, age, phone_num, Address, Reg_num):
    print(f"I'am {name},my age is {age},my pno is { phone_num}, andddd my adress { Address}, my reg number is {Reg_num}")
college(age=19, name="Rekha", phone_num="343234568",
        Address="koppal", Reg_num="80")


I'am Rekha,my age is 19,my pno is 343234568, andddd my adress koppal, my reg number is 80


In [ ]:
def hello(country="India 🚩"):
    print("I love", country)

hello("India 💕")
hello("Pakistan 💖")
hello("America (❁´◡`❁)")
hello()


I love India 💕
I love Pakistan 💖
I love America (❁´◡`❁)
I love India 🚩


In [ ]:
def student(*marks):
  for i in marks:
    print(i)
student(1,2,3,4,5,)

1
2
3
4
5


In [ ]:
def student(*marks):
    sum = 0
    avg=len(marks)

    for i in marks:
        sum = sum + i
    print("sum =", sum)
    print("avg value", sum/avg)
    print("the max value is", max(marks))
    print("the min value is", min(marks))
student(1, 2, 3, 4, 5)
student(5,10,25,40,55,70,95,110)


sum = 15
avg value 3.0
the max value is 5
the min value is 1
sum = 410
avg value 51.25
the max value is 110
the min value is 5


In [ ]:
def fun(**kwargs):
  for key, value in kwargs.items():
    print(f"{key}: {value}")
fun(Reg=124,Name="suvrna", Age = 22, place = "Raichur")
fun(Reg=124,Name="suvrna", Age = 22, place = "Raichur")

Reg: 124
Name: suvrna
Age: 22
place: Raichur


In [ ]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
import numpy as n
arr=n.zeros((10,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
import numpy as np
arr=np.ones((5,7))
arr


array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
import numpy as np
arr=np.full((4,7),9)
arr

array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]])

In [ ]:
arr = np.zeros((5, 5))
print(arr)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
import numpy as np
arr = np.arange(2,100,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
import numpy as np
Even=np.arange(2,200,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
import numpy as np
arr= np. arange( 1,100,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
import numpy as np
arr= np. linspace(1,20,5)
arr

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [ ]:
import numpy as np
arr=np.random.rand(10)
arr

array([0.16442185, 0.50721903, 0.14551736, 0.95425455, 0.5252781 ,
       0.58565605, 0.13824303, 0.51723915, 0.28459359, 0.14788193])

In [ ]:
import numpy as np
arr=np.random.randn(10)
arr

array([-0.07590602,  0.90789167,  0.63971647,  0.58543052,  2.19100398,
        0.07445916,  1.45700245,  0.23427489, -0.2172624 ,  0.73852652])

In [ ]:
import numpy as np
arr=np.random.randint(100)
arr

55

In [ ]:
import numpy as np
colours=["red","green"]
print(np.random.choice(colours,2))

['green' 'green']


In [ ]:
import numpy as np
arr=np.array([1,2,3])
new = arr.copy()
new[1]=100
print("array value is :",arr)
print("copy value is :",new)

array value is : [1 2 3]
copy value is : [  1 100   3]


In [ ]:
import numpy as np
arr = np.array([1,2,3])
new = arr.view()
new[1]=100
print("Array value is:",arr)
print(" view value us:",new)

Array value is: [  1 100   3]
 view value us: [  1 100   3]


In [ ]:
import numpy as np
arr=np.array([5,10,15,20,25,30])
arr += 10
print("upadated array value is :",arr)

upadated array value is : [15 20 25 30 35 40]


In [ ]:
import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,0])
print(np.add(A,B))

[ 7  9 11 13  5]


In [ ]:
import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,0])
print(np.subtract(A,B))

[-5 -5 -5 -5  5]


In [ ]:
import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,0])
print(np.divide(A,B))

[0.16666667 0.28571429 0.375      0.44444444        inf]


/tmp/ipykernel_4852/3735694853.py:4: RuntimeWarning: divide by zero encountered in divide
  print(np.divide(A,B))


In [ ]:
import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,0])
print(np.multiply(A,B))

[ 6 14 24 36  0]


In [ ]:
import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
print(np.dot(A,B))

130


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,])
print(sum(arr))


45


In [ ]:
import numpy as np
arr=np.array([1,2,34,5,54,3,3,83,3,])
print(sum(arr))
print("minimum number is",min(arr))
print("maximum number is",max(arr))
print(np.sort(arr))
print(np.mean(arr))
print(np.sqrt(arr))
print(np.unique(arr))
print(arr.shape)
print(arr.size)
print(arr.itemsize)
print(arr.ndim)
print(arr.dtype)


188
minimum number is 1
maximum number is 83
[ 1  2  3  3  3  5 34 54 83]
20.88888888888889
[1.         1.41421356 5.83095189 2.23606798 7.34846923 1.73205081
 1.73205081 9.11043358 1.73205081]
[ 1  2  3  5 34 54 83]
(9,)
9
8
1
int64


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
print(arr.ndim)
print(np.unique(arr))
print(arr.shape)
print(arr.size)
print(arr.itemsize)
print(arr.ndim)
print(arr.dtype)
print(arr[:,1])



(2, 4)
2
[1 2 3 4 5 6 7 8]
(2, 4)
8
8
2
int64
[2 6]


In [ ]:
import numpy as np
arr=np.array((1,2,3,4,5,6,7,8,9,10))
print("Original array",arr)
new=arr.reshape(2,5)
print(new)

Original array [ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
